AWSTemplateFormatVersion: '2010-09-09'
Description: Nested stack for VPC and EC2 deployment
Parameters:
  EnvId:
    Type: String
    Default: SimpleVPCAlexei-XStack
    Description: Environment name tag/prefix
  KeyName:
    Type: String
    Default: ''
    Description: Name of an existing EC2 KeyPair to enable SSH access (optional)
Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-2.amazonaws.com/infra-backend-infrabackendbucket-f1f3dahhukfo/c775f764fd0cfe02bbea5dedb984acc8.template
      Parameters:
        AlexeiEnvironment:
          Ref: EnvId
  EC2Stack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL: https://s3.us-east-2.amazonaws.com/infra-backend-infrabackendbucket-f1f3dahhukfo/568d1ced5ae19fad8d96b3f9be8f84c4.template
      Parameters:
        EnvId:
          Ref: EnvId
        NetworkStackName:
          Ref: EnvId
        KeyName:
          Ref: KeyName
Outputs:
  VPCID:
    Description: VPC ID
    Value:
      Fn::GetAtt:
      - VPCStack
      - Outputs.VPC
  InstancePublicIP:
    Description: EC2 public IP
    Value:
      Fn::GetAtt:
      - EC2Stack
      - Outputs.InstancePublicIP
  WebURL:
    Description: Web URL
    Value:
      Fn::GetAtt:
      - EC2Stack
      - Outputs.WebURL
